# Generated by Django 4.0.3 on 2022-03-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('povoados', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_conexao', models.CharField(choices=[('A', 'Adultos'), ('J', 'Jovens')], max_length=1)),
                ('dia_semana_reuniao', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-Feira'), ('3', 'Terça-Feira'), ('4', 'Quarta-Feira'), ('5', 'Quinta-Feira'), ('6', 'Sexta-Feira'), ('7', 'Sábado')], max_length=1)),
                ('hora_reuniao', models.TimeField(max_length=6)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('updated', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Líder', to='pessoas.pessoa')),
                ('participantes', models.ManyToManyField(to='pessoas.pessoa')),
                ('povoado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='povoados.povoado', verbose_name='Povoado')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
            },
        ),
    ]
