# Generated by Django 4.0.3 on 2022-03-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('conexao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conexao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='conexao',
            name='complemento',
        ),
        migrations.AlterField(
            model_name='conexao',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Líder', to='pessoas.pessoa'),
        ),
    ]
