# Generated by Django 4.0.3 on 2022-03-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Povoado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(blank=True, default='Miguel Calmon', max_length=50, null=True)),
                ('uf', models.CharField(blank=True, default='BA', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('updated', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('missionário', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missionário', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Povoados',
            },
        ),
    ]
